--- #YAML:1.0
name:                CPAN-Mini
version:             0.562
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Compress::Zlib:                1.20
    File::HomeDir:                 0.57
    LWP:                           5
    Pod::Usage:                    1
    URI:                           1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
