--- 
abstract: create a minimal mirror of CPAN
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CPAN-Mini
no_index: 
  directory: 
    - inc
    - t
requires: 
  Compress::Zlib: 1.20
  File::HomeDir: 0.57
  LWP: 5
  Pod::Usage: 1.00
  URI: 1
  perl: 5.6.0
tests: t/*.t xt/*.t
version: 0.571



